load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "lib",
    srcs = ["hello-time.cc"],
    hdrs = [
        "hello-time.hpp",
        "Cuboid.hpp", "Cuboid.cc"
    ],
    visibility = ["//main:__pkg__"],
)
